name: Fetch Met Éireann Forecast

on:
  schedule:
    - cron: '10 0 * * *'  # daily at 00:10 UTC
  workflow_dispatch:      # allows manual run

jobs:
  fetch_forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Met Éireann XML
        run: |
          mkdir -p forecast_data
          curl -s "http://openaccess.pf.api.met.ie/metno-wdb2ts/locationforecast?lat=55.267;long=-7.633" -o forecast_data/raw_forecast.xml

      - name: Convert XML to JSON
        run: |
          python3 - << 'EOF'
          import xml.etree.ElementTree as ET
          import json, datetime

          tree = ET.parse('forecast_data/raw_forecast.xml')
          root = tree.getroot()

          # Filter for 26 Aug 2025
          start = datetime.datetime(2025,8,26)
          end = datetime.datetime(2025,8,27)
          forecasts = []

          # Iterate all forecast-time entries
          for ft in root.findall('.//forecast-time'):
              t = datetime.datetime.fromisoformat(ft.attrib['time'])
              if not (start <= t < end):
                  continue
              entry = {'time': ft.attrib['time']}
              for p in ft.findall('Parameter'):
                  name = p.attrib.get('name')
                  value_elem = p.find('value')
                  if value_elem is not None:
                      entry[name] = value_elem.text
              forecasts.append(entry)

          # If no data found, create at least a placeholder entry
          if not forecasts:
              forecasts.append({
                  "time": "2025-08-26T12:00:00",
                  "Temperature": "N/A",
                  "Rainfall": "0.0",
                  "TotalCloudCover": "N/A",
                  "WindSpeed": "0",
                  "WindDirection": "0",
                  "WeatherSymbol3": "1"
              })

          with open('forecast_data/forecast.json','w') as f:
              json.dump(forecasts, f, indent=2)
          EOF

      - name: Commit and push forecast.json
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add forecast_data/forecast.json
          git commit -m "Update forecast.json [skip ci]" || echo "No changes"
          git push
