name: Fetch Met Éireann Forecast

on:
  schedule:
    # Every day at 00:10 UTC
    - cron: '10 0 * * *'
  workflow_dispatch: # allows manual run

jobs:
  fetch_forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Met Éireann Forecast
        run: |
          mkdir -p forecast_data
          curl -s "http://openaccess.pf.api.met.ie/metno-wdb2ts/locationforecast?lat=55.267;long=-7.633" -o forecast_data/raw_forecast.xml
          
          # Convert XML to JSON using python
          python3 - << 'EOF'
          import xml.etree.ElementTree as ET
          import json
          tree = ET.parse('forecast_data/raw_forecast.xml')
          root = tree.getroot()

          # Only keep relevant forecast-time elements for 26 Aug 2025
          import datetime
          start = datetime.datetime(2025, 8, 26)
          end = datetime.datetime(2025, 8, 27)
          forecasts = []

          for ft in root.findall('.//forecast-time'):
              t_str = ft.attrib['time']
              t = datetime.datetime.fromisoformat(t_str)
              if not (start <= t < end):
                  continue
              entry = {'time': t_str}
              for p in ft.findall('Parameter'):
                  name = p.attrib.get('name')
                  value = p.findtext('value')
                  entry[name] = value
              forecasts.append(entry)

          with open('forecast_data/forecast.json', 'w') as f:
              json.dump(forecasts, f, indent=2)
          EOF

      - name: Commit and push forecast.json
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add forecast_data/forecast.json
          git commit -m "Update forecast.json [skip ci]" || echo "No changes"
          git push

