name: Fetch Weather Forecast (Aug 28–31)

on:
  schedule:
    - cron: "0 * * * *"   # every hour on the hour
  workflow_dispatch:

jobs:
  fetch-forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch and save forecast
        run: |
          python3 - <<'PYCODE'
          import requests
          import json
          from datetime import datetime

          # Coordinates for courses
          coords = {
              "Portsalon_28Aug": (55.2056262, -7.6350788),
              "Downings_29Aug": (55.1948628, -7.8369654),
              "Downings_30Aug": (55.1948628, -7.8369654),
              "Downings_31Aug": (55.1948628, -7.8369654),
          }

          # Dates for each day
          start_dates = {
              "Portsalon_28Aug": "2025-08-28",
              "Downings_29Aug": "2025-08-29",
              "Downings_30Aug": "2025-08-30",
              "Downings_31Aug": "2025-08-31",
          }

          forecasts = []

          for group, (lat, lon) in coords.items():
              date = start_dates[group]
              url = (
                  f"https://api.open-meteo.com/v1/forecast?"
                  f"latitude={lat}&longitude={lon}"
                  f"&hourly=temperature_2m,precipitation,weathercode,windspeed_10m,winddirection_10m"
                  f"&timezone=auto&start_date={date}&end_date={date}"
              )
              r = requests.get(url)
              data = r.json()

              times = data["hourly"]["time"]
              temps = data["hourly"]["temperature_2m"]
              winds = data["hourly"]["windspeed_10m"]
              dirs = data["hourly"]["winddirection_10m"]
              rains = data["hourly"]["precipitation"]
              codes = data["hourly"]["weathercode"]

              for t, temp, ws, wd, rain, code in zip(times, temps, winds, dirs, rains, codes):
                  # Only between 7:00 and 19:00 inclusive
                  hour = int(t[11:13])
                  if 7 <= hour <= 19:
                      forecasts.append({
                          "group": group,
                          "time": t,
                          "Temperature": temp,
                          "WindDirection": wd,
                          "WindSpeed": ws,
                          "Rainfall": rain,
                          "WeatherSymbol3": str(code).zfill(2)
                      })

          output = {
              "timestamp": datetime.utcnow().strftime("%Y-%m-%d %H:%M"),
              "forecasts": forecasts
          }

          # Save file
          import os
          os.makedirs("forecast_data", exist_ok=True)
          with open("forecast_data/forecast.json", "w") as f:
              json.dump(output, f, indent=2)
          PYCODE

      - name: Commit forecast.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add forecast_data/forecast.json
          git commit -m "Update forecast data" || echo "No changes to commit"
          git push
