name: Fetch Weather Forecast & Met Éireann Icons

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

jobs:
  fetch-forecast-and-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch and save forecast
        run: |
          python3 - <<'PYCODE'
          import requests
          import json
          from datetime import datetime
          import xml.etree.ElementTree as ET
          import os

          coords = {
              "Portsalon_28Aug": (55.2056262, -7.6350788),
              "Downings_29Aug": (55.1948628, -7.8369654),
              "Downings_30Aug": (55.1948628, -7.8369654),
              "Downings_31Aug": (55.1948628, -7.8369654),
          }

          forecasts = []

          for group, (lat, lon) in coords.items():
              url = f"http://openaccess.pf.api.met.ie/metno-wdb2ts/locationforecast?lat={lat};long={lon}"
              try:
                  r = requests.get(url, timeout=10)
                  r.raise_for_status()
                  root = ET.fromstring(r.content)
              except Exception as e:
                  print(f"Error fetching {group}: {e}")
                  continue

              # Parse XML: <time><location>...</location></time>
              for time_item in root.findall(".//time"):
                  t = time_item.attrib.get("from")
                  if not t:
                      continue
                  hour = int(t[11:13])
                  if not (7 <= hour <= 19):
                      continue

                  loc = time_item.find("location")
                  if loc is None:
                      continue

                  temp = loc.find("temperature")
                  rain = loc.find("precipitation")
                  wind_speed = loc.find("windSpeed")
                  wind_dir = loc.find("windDirection")
                  symbol = loc.find("symbol")

                  forecasts.append({
                      "group": group,
                      "time": t,
                      "Temperature": round(float(temp.attrib["value"]), 1) if temp is not None else None,
                      "WindDirection": round(float(wind_dir.attrib.get("deg",0)), 0) if wind_dir is not None else None,
                      "WindSpeed": round(float(wind_speed.attrib.get("mps",0))*3.6,1) if wind_speed is not None else None,
                      "Rainfall": round(float(rain.attrib.get("value",0)),2) if rain is not None else 0,
                      "WeatherSymbol": symbol.attrib.get("number") if symbol is not None else "01"
                  })

          output = {
              "timestamp": datetime.utcnow().isoformat() + "Z",
              "forecasts": forecasts
          }

          os.makedirs("forecast_data", exist_ok=True)
          with open("forecast_data/forecast.json", "w") as f:
              json.dump(output, f, indent=2)
          PYCODE

      - name: Download Met Éireann icons (01.png → 52.png)
        run: |
          mkdir -p forecast_icons
          for i in $(seq -w 1 52); do
            curl -s -o forecast_icons/${i}.png https://www.met.ie/cms/assets/uploads/2018/01/${i}.png
          done
          # fallback icon
          curl -s -o forecast_icons/00.png https://www.met.ie/cms/assets/uploads/2018/01/01.png

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add forecast_data/forecast.json forecast_icons/
          git diff --cached --quiet || git commit -m "Update forecast data and icons"
          git push
