name: Update Forecast

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Fetch and process forecast
        run: |
          pip install requests xmltodict

          python - << 'PYCODE'
          import requests, xmltodict, json
          from datetime import datetime

          url = "https://www.met.ie/Open_Data/xml/PointForecasts/55.2670,-7.6330.xml"
          xml_data = requests.get(url).text
          data = xmltodict.parse(xml_data)

          forecasts = []
          seen = set()

          for time in data["weatherdata"]["product"]["time"]:
              ts = time["@from"]
              hour = datetime.fromisoformat(ts.replace("Z", "+00:00")).hour

              if 12 <= hour <= 18 and ts not in seen:
                  seen.add(ts)
                  loc = time["location"]
                  entry = {
                      "time": ts,
                      "temperature": loc.get("temperature", {}).get("@value"),
                      "windSpeed": loc.get("windSpeed", {}).get("@mps"),
                      "windDir": loc.get("windDirection", {}).get("@name"),
                      "gust": loc.get("windGust", {}).get("@mps"),
                      "humidity": loc.get("humidity", {}).get("@value"),
                      "pressure": loc.get("pressure", {}).get("@value"),
                      "precipitation": loc.get("precipitation", {}).get("@value") if "precipitation" in loc else None,
                      "symbol": loc.get("symbol", {}).get("@id") if "symbol" in loc else None
                  }
                  forecasts.append(entry)

          with open("SLIM/SLIM2025/forecast.json", "w") as f:
              json.dump(forecasts, f, indent=2)
          PYCODE

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add SLIM/SLIM2025/forecast.json
          git commit -m "Update forecast" || echo "No changes"
          git push
