name: Fetch Met Éireann Forecast

on:
  schedule:
    - cron: '0 * * * *'  # Every hour on the hour UTC
  workflow_dispatch:

jobs:
  fetch_forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Met Éireann XML
        run: |
          mkdir -p forecast_data
          curl -s "http://openaccess.pf.api.met.ie/metno-wdb2ts/locationforecast?lat=55.267;long=-7.633" -o forecast_data/raw_forecast.xml

      - name: Convert XML to JSON
        run: |
          python3 - <<'PY'
          import xml.etree.ElementTree as ET
          import json
          import datetime
          import pytz

          tree = ET.parse('forecast_data/raw_forecast.xml')
          root = tree.getroot()

          tz = pytz.UTC
          start = datetime.datetime(2025, 8, 28, tzinfo=tz)
          end   = datetime.datetime(2025, 8, 31, 23, 59, tzinfo=tz)

          forecasts_dict = {}

          for time_el in root.findall('.//time'):
              time_str = time_el.attrib.get('from')
              if not time_str:
                  continue

              dt = datetime.datetime.fromisoformat(time_str.replace('Z', '+00:00'))
              if not (start <= dt <= end):
                  continue

              loc = time_el.find('location')
              if loc is None:
                  continue

              # Determine group
              day = dt.day
              group = None
              if day == 28: group = "Portsalon_28Aug"
              elif day == 29: group = "Downings_29Aug"
              elif day == 30: group = "Downings_30Aug"
              elif day == 31: group = "Downings_31Aug"

              key = group + "_" + dt.isoformat()
              if key not in forecasts_dict:
                  forecasts_dict[key] = {'group': group, 'time': dt.isoformat()}

              entry = forecasts_dict[key]

              # Merge values
              temp = loc.find('temperature')
              if temp is not None:
                  entry['Temperature'] = float(temp.attrib.get('value', entry.get('Temperature', 0)))

              winddir = loc.find('windDirection')
              if winddir is not None:
                  entry['WindDirection'] = float(winddir.attrib.get('deg', entry.get('WindDirection', 0)))

              windspeed = loc.find('windSpeed')
              if windspeed is not None:
                  entry['WindSpeed'] = float(windspeed.attrib.get('mps', 0)) * 3.6  # m/s -> km/h

              precip = loc.find('precipitation')
              if precip is not None:
                  entry['Rainfall'] = float(precip.attrib.get('value', entry.get('Rainfall', 0)))

              symbol = loc.find('symbol')
              if symbol is not None:
                  entry['WeatherSymbol3'] = symbol.attrib.get('number', entry.get('WeatherSymbol3'))

          forecasts = list(forecasts_dict.values())

          output = {
              "timestamp": datetime.datetime.now(tz).isoformat(),
              "forecasts": forecasts
          }

          with open('forecast_data/forecast.json', 'w') as f:
              json.dump(output, f, indent=2)

          print(f"Wrote {len(forecasts)} forecast entries to forecast_data/forecast.json")
          PY

      - name: Commit and push forecast.json
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add forecast_data/forecast.json
          git commit -m "Update forecast.json [skip ci]" || echo "No changes"
          git push
